version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Vectorquest-app
    restart: unless-stopped
    tty: true
    ports:
      - 4000:4000  
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /go/src/Vectorquest
    command: go run main.go
    volumes:
      - ./:/go/src/Vectorquest
    networks:
      - app


  db:
     image: postgres
     networks:
       app:
         aliases:
           - database
     environment:
       POSTGRES_DB: vectorquest
       POSTGRES_PASSWORD: 1117111
     ports:
       - "5432"
     volumes:
      - dbvquest:/var/lib/postgresql/data

  migrate:
      image: migrate/migrate
      networks:
        - app
      volumes:
        - ./db/migrations:/migrations
      command: [ "-path", "/migrations", "-database",  "postgres://postgres:1117111@db:5432/vectorquest?sslmode=disable", "up"]
      links:
         - db

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1117111
    ports:
      - "8080:80"
    networks:
      - app  

networks:
  app:
    driver: bridge

volumes:
  dbvquest:
    driver: local
